"""
Необхідно створити функцію generator_numbers, яка буде аналізувати текст,
ідентифікувати всі дійсні числа, що вважаються частинами доходів,
і повертати їх як генератор. Дійсні числа у тексті записані без помилок,
чітко відокремлені пробілами з обох боків.
Також потрібно реалізувати функцію sum_profit, яка буде використовувати
generator_numbers для підсумовування цих чисел і обчислення загального прибутку.
"""
import re
from typing import Callable


def generator_numbers(text: str):
    """
    Finds all real numbers and turns them to generator
    :param text: str
    """
    pattern = r'\d+.\d+'
    matches = re.findall(pattern, text)

    # for match in matches:
    #     yield match
    yield from matches


def sum_profit(text: str, func: Callable):
    """
    Sums all numbers generated by func in text
    :param text: str
    :param func: Callable
    :return: sum: int
    """
    result = 0
    for item in func(text):
        result += float(item)
    return result


if __name__ == '__main__':
    TEST = ("Загальний дохід працівника складається з декількох частин: "
            "1000.01 як основний дохід, доповнений додатковими "
            "надходженнями 27.45 і 324.00 доларів.")

    total_income = sum_profit(TEST, generator_numbers)
    print(f"Загальний дохід: {total_income}") # Загальний дохід: 1351.46
